export const REQUEST_GRACERY_LIST ='REQUEST_GRACERY_LIST';
export const RECEIVE_GRACERY_LIST ='RECEIVE_GRACERY_LIST';
export const RECEIVE_GRACERY_LIST_ERROR ='RECEIVE_GRACERY_LIST_ERROR';
export const RECEIVE_GRACERY_LIST_NETWORK_ERROR ='RECEIVE_GRACERY_LIST_NETWORK_ERROR';
