export const REQUEST_GROCERY_LIST ='REQUEST_GROCERY_LIST';
export const RECEIVE_GROCERY_LIST ='RECEIVE_GROCERY_LIST';
export const RECEIVE_GROCERY_LIST_ERROR ='RECEIVE_GROCERY_LIST_ERROR';
export const RECEIVE_GROCERY_LIST_NETWORK_ERROR ='RECEIVE_GROCERY_LIST_NETWORK_ERROR';

export const REQUEST_SAVE_GROCERY = 'REQUEST_SAVE_GROCERY';
export const RECEIVE_SAVE_GROCERY= 'RECEIVE_SAVE_GROCERY';
export const RECEIVE_SAVE_GROCERY_ERROR= 'RECEIVE_SAVE_GROCERY_ERROR';


export const REQUEST_GROCERY_BY_ID ='REQUEST_GROCERY_BY_ID';
export const RECEIVE_GROCERY_BY_ID ='RECEIVE_GROCERY_BY_ID';
export const RECEIVE_GROCERY__BY_ID_ERROR ='RECEIVE_GROCERY__BY_ID_ERROR';
