export const REQUEST_GROCERY_LIST ='REQUEST_GROCERY_LIST';
export const RECEIVE_GROCERY_LIST ='RECEIVE_GROCERY_LIST';
export const RECEIVE_GROCERY_LIST_ERROR ='RECEIVE_GROCERY_LIST_ERROR';
export const RECEIVE_GROCERY_LIST_NETWORK_ERROR ='RECEIVE_GROCERY_LIST_NETWORK_ERROR';
